# Generated by Django 5.0.6 on 2024-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("instructions", models.TextField(max_length=2000)),
                (
                    "tools",
                    models.CharField(
                        choices=[
                            ("code_interpreter", "Code Interpreter"),
                            ("file_search", "File Search"),
                        ],
                        max_length=50,
                    ),
                ),
                ("vectorStore", models.BinaryField()),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("gpt-4o", "gpt-4o"),
                            ("gpt-4-turbo", "gpt-4-turbo"),
                            ("gpt-4-turbo-2024-04-09", "gpt-4-turbo-2024-04-09"),
                            ("gpt-4-0125-preview", "gpt-4-0125-preview"),
                            ("gpt-4-1106-preview", "gpt-4-1106-preview"),
                            ("gpt-4-0613", "gpt-4-0613"),
                            ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                            ("gpt-3.5-turbo-1106", "gpt-3.5-turbo-1106"),
                            ("gpt-3.5-turbo-instruct", "gpt-3.5-turbo-instruct"),
                            (
                                "llama-3-sonar-small-32k-online",
                                "llama-3-sonar-small-32k-online",
                            ),
                            (
                                "llama-3-sonar-small-32k-chat",
                                "llama-3-sonar-small-32k-chat",
                            ),
                            (
                                "llama-3-sonar-large-32k-online",
                                "llama-3-sonar-large-32k-online",
                            ),
                            (
                                "llama-3-sonar-large-32k-chat",
                                "llama-3-sonar-large-32k-chat",
                            ),
                            (
                                "claude-3-5-sonnet-20240620",
                                "claude-3-5-sonnet-20240620",
                            ),
                            ("claude-3-opus-20240229", "claude-3-opus-20240229"),
                            ("claude-3-sonnet-20240229", "claude-3-sonnet-20240229"),
                            ("claude-3-haiku-20240307", "claude-3-haiku-20240307"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("title", models.CharField(max_length=200)),
                ("header_color", models.CharField(max_length=7)),
                ("assistant_color", models.CharField(max_length=7)),
                ("user_color", models.CharField(max_length=7)),
                ("assistant_start_message", models.TextField(max_length=2000)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
