# Generated by Django 5.0.6 on 2024-07-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vectorstore",
            name="upload",
        ),
    ]
