# Generated by Django 5.0.6 on 2024-07-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0002_remove_assistant_vectorstore_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
