# Generated by Django 5.0.6 on 2024-07-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0002_remove_vectorstore_upload"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VectorStore",
        ),
    ]
