# Generated by Django 5.0.6 on 2024-07-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0003_delete_vectorstore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
