# Generated by Django 5.0.6 on 2024-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0003_assistant_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="website",
            field=models.TextField(max_length=5000),
        ),
    ]
