# Generated by Django 5.0.6 on 2024-07-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customization", "0006_remove_assistant_website_assistant_websites"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="suggested_responses",
            field=models.JSONField(default=list),
        ),
    ]
